### ISSUE TITLE
bug(installer): gsd-tools CLI crashes at load — scripts/fix-slash-commands.cjs missing from install, every gsd_run fails (regression since 1.5.0-rc.1)

### ISSUE THREAD

**Issue by jslitzkerttcu** [open-gsd/gsd-core#1223]
### Pre-submission

- [x] I have searched existing issues and this bug has not already been reported. (Searched: `fix-slash-commands`, `command-roster`, `MODULE_NOT_FOUND`, "cannot find module", "install scripts missing", `init.new-project`. Closest relatives are #935 and #606 — same *installer-omits-a-required-file* family, but a different file; none cover `scripts/fix-slash-commands.cjs`.)

### GSD Version

`1.5.0-rc.3` (from `~/.claude/gsd-core/VERSION`)

### Runtime

Claude Code

### Operating System

macOS (Darwin 25.6.0, Apple Silicon)

### Node.js Version

`v26.0.0`

### Installation Method

Global install into `~/.claude` (updated/reinstalled to `1.5.0-rc.3`).

### What happened?

**Every** GSD command that shells out to the `gsd-tools` CLI crashes at module-load time, so no workflow can run. I hit it on `/gsd-new-project`, which aborts at Step 1 (Setup) on its first `gsd_run query init.new-project` call:

```
Error: Cannot find module '../../../scripts/fix-slash-commands.cjs'
Require stack:
- ~/.claude/gsd-core/bin/lib/command-roster.cjs
- ~/.claude/gsd-core/bin/lib/runtime-artifact-conversion.cjs
- ~/.claude/gsd-core/bin/lib/runtime-artifact-layout.cjs
- ~/.claude/gsd-core/bin/lib/surface.cjs
- ~/.claude/gsd-core/bin/lib/capability-state.cjs
- ~/.claude/gsd-core/bin/lib/loop-resolver.cjs
- ~/.claude/gsd-core/bin/gsd-tools.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1475:15)
  code: 'MODULE_NOT_FOUND'
```

Because the throw is at **module load** of a core dependency in the `gsd-tools.cjs` require chain, it is not specific to `new-project` — any `gsd_run query …` (config, commit, state, roadmap, plan, etc.) fails identically. `/gsd-new-project` wrote nothing (no `.planning/` created), so at least the failure is clean.

### What did you expect?

`node ~/.claude/gsd-core/bin/gsd-tools.cjs query init.new-project` should load and emit JSON, and `/gsd-new-project` should proceed past Step 1.

### Steps to reproduce

1. Install/update GSD `1.5.0-rc.3` globally into `~/.claude` (Claude Code runtime).
2. Run any GSD workflow, e.g. `/gsd-new-project`, or invoke the CLI directly:
   ```
   node ~/.claude/gsd-core/bin/gsd-tools.cjs query init.new-project
   ```
3. Observe the `MODULE_NOT_FOUND` crash above.

### How often does this happen?

Every time.

### Impact

Blocker — the entire CLI is unusable; no GSD command can run.

### Error output / logs

See the require-stack trace above.

### Root cause analysis

`bin/lib/command-roster.cjs` (compiled from `src/command-roster.cts`) does, at line 9:

```js
const slashCommandTransformer = require('../../../scripts/fix-slash-commands.cjs');
```

From the installed location `~/.claude/gsd-core/bin/lib/command-roster.cjs`, `../../../scripts/` resolves to **`~/.claude/scripts/fix-slash-commands.cjs`** (i.e. `scripts/` is expected to be a *sibling of* `gsd-core/`, not inside it — which matches the repo dev layout where `gsd-core/` and `scripts/` are siblings at repo root).

On this install:

- `~/.claude/scripts/` **exists** and contains `changeset/` and `lib/`.
- `~/.claude/scripts/fix-slash-commands.cjs` **does not exist**.
- There is **no** `scripts/` directory inside `~/.claude/gsd-core/` either (only `bin contexts references templates workflows VERSION`).

So the installer's copy manifest deploys part of `scripts/` (e.g. `scripts/changeset/…`, cf. #935) but **omits the top-level file `scripts/fix-slash-commands.cjs`** that `command-roster.cjs` hard-requires at load. In the repo this file lives at `scripts/fix-slash-commands.cjs` and is depended on by `src/command-roster.cts` plus several tests (`tests/bug-2543-*`, `bug-2808-*`, `bug-3677-*`, `bug-3683-*`), so it is a shipped runtime dependency, not test-only.

This is the same defect class as:
- #935 — `scripts/changeset/cli.cjs` not installed (+ wrong path)
- #606 — installer does not copy `hooks/managed-hooks-registry.cjs`, crashing the update checker

Suggested fix direction (for maintainers): add `scripts/fix-slash-commands.cjs` to the installer copy manifest so it lands where `command-roster.cjs`'s `../../../scripts/` require resolves (`~/.claude/scripts/fix-slash-commands.cjs`), with a release-tarball/smoke assertion that the file is present and `gsd-tools query` loads — mirroring the guards added for #935/#606.

### Regression window

This is a **regression**: GSD worked fine on `1.5.0-rc.1`. It is broken on `1.5.0-rc.3`. `1.5.0-rc.2` was not tested, so the break was introduced in **rc.2 or rc.3** — likely a change to the installer copy manifest or to the `command-roster.cjs` require path in that window. (Possibly related: #1099 "Extract runtime artifact conversion module" introduced `runtime-artifact-conversion.cjs`, which sits in this require chain.)

I have **not** verified whether the current stable release is affected — I briefly switched to it only to get the tools to install, then reinstalled rc.3 *before* testing, so stable is untested here.

### Privacy

- [x] I have reviewed for PII and redacted absolute home paths to `~`. No tokens, keys, or credentials are included.

**Comment by jslitzkerttcu** [comment]
### Local workaround (unblocks without reverting versions)

The installer omits exactly one file: `scripts/fix-slash-commands.cjs`. The `command-roster.cjs` require resolves to `<install-root>/scripts/fix-slash-commands.cjs` (i.e. a sibling of `gsd-core/`, `commands/`, `agents/`, `hooks/`), and the file's own `__dirname/..` paths confirm that's its intended home. Dropping the matching version into place restores the CLI — no downgrade needed.

For a global Claude Code install at `~/.claude` on `1.5.0-rc.3`:

```sh
# Fetch the file the installer should have copied, at your installed version
VER=$(cat ~/.claude/gsd-core/VERSION)          # e.g. 1.5.0-rc.3
curl -fsSL "https://raw.githubusercontent.com/open-gsd/gsd-core/v${VER}/scripts/fix-slash-commands.cjs" \
  -o ~/.claude/scripts/fix-slash-commands.cjs

# Verify the CLI loads again
node ~/.claude/gsd-core/bin/gsd-tools.cjs query init.new-project   # should print JSON, not MODULE_NOT_FOUND
```

Confirmed working here: after copying, `gsd-tools query init.new-project` returns valid JSON (exit 0) and `/gsd-new-project` proceeds past Step 1.

### Second, latent failure on installs without `commands/gsd/`

On this Claude Code install there is **no** `~/.claude/commands/` directory (GSD commands are registered as skills), and `readCmdNames()` does an unguarded `fs.readdirSync(COMMANDS_DIR)` against `<install-root>/commands/gsd`. So even after the file is restored, any code path that calls `readGsdCommandNames()` / `readCmdNames()` would throw a *second* `ENOENT`. It didn't trigger for `init.new-project`, but it's a landmine.

A one-line defensive guard makes it resilient (returns `[]` when the dir is absent, same as the existing `try/catch` no-ops on `findFiles`/`processFile`):

```js
function readCmdNames() {
  let entries;
  try { entries = fs.readdirSync(COMMANDS_DIR); } catch { return []; }
  return entries
    .filter(f => f.endsWith('.md'))
    .map(f => f.replace(/\.md$/, ''));
}
```

Maintainers may want both: (1) add `scripts/fix-slash-commands.cjs` to the installer copy manifest + a release-tarball/smoke assertion that the file is present and `gsd-tools query` loads (mirroring the #935 / #606 guards), and (2) harden `readCmdNames()` for installs lacking a `commands/gsd` dir.

**Comment by trek-e** [comment]
> *This was generated by AI during triage.*

## Agent Brief

**Category:** bug — **P0 install blocker** (regression introduced by PR #1100 / refactor #1099, merged 2026-06-13)
**Summary:** The installer omits `scripts/fix-slash-commands.cjs`, which `command-roster` hard-requires at module load, so every `gsd-tools` invocation crashes with `MODULE_NOT_FOUND` on installed runtimes.

**Current behavior:**
On a fresh or updated install (1.5.0-rc.2+), any `gsd-tools query …` crashes at module load:
`Error: Cannot find module '../../../scripts/fix-slash-commands.cjs'`, via the require chain gsd-tools → loop-resolver → capability-state → surface → runtime-artifact-layout → runtime-artifact-conversion → command-roster. Because the throw is at load of a core dependency, **every** GSD workflow fails identically (not just `new-project`). The installer copy manifest deploys `scripts/changeset/` and `scripts/lib/` but never the top-level file `scripts/fix-slash-commands.cjs` — even though `command-roster` requires it and it ships in the npm tarball. Verified at HEAD: from the installed `gsd-core/bin/lib/command-roster.cjs`, the require resolves to `<install-root>/scripts/fix-slash-commands.cjs` (a sibling of `gsd-core/`), which the installer never creates. Same defect class as #935 (`scripts/changeset/cli.cjs`) and #606 (`hooks/managed-hooks-registry.cjs`).

A **second, latent** failure: `readCmdNames()` (in `scripts/fix-slash-commands.cjs`) does an unguarded `fs.readdirSync(<install-root>/commands/gsd)`. On installs that register GSD as skills (no `commands/gsd` directory — e.g. Claude Code), any path that reaches it throws `ENOENT` once the first crash is fixed.

**Desired behavior:**
- The installer copies `scripts/fix-slash-commands.cjs` to `<install-root>/scripts/fix-slash-commands.cjs` so the `command-roster` require resolves on every runtime; `gsd-tools query` loads and emits JSON.
- A release-tarball/smoke assertion verifies the file is present and that `gsd-tools query` loads without `MODULE_NOT_FOUND` (mirroring the guards added for #935/#606), so this regression cannot recur silently.
- `readCmdNames()` degrades gracefully (returns `[]`) when its commands directory is absent, matching the existing try/catch no-ops in that module.

**Key interfaces:**
- Installer copy manifest, written-manifest hash list, and uninstall removal list (currently `bin/install.js`, generated — edit the source it builds from) — add `scripts/fix-slash-commands.cjs` alongside the existing `scripts/changeset/` handling.
- `readCmdNames()` in `scripts/fix-slash-commands.cjs` — wrap the `readdirSync` in try/catch returning `[]` on failure.
- Install smoke test (currently `tests/install.test.cjs`) — assert the file lands at `<configDir>/scripts/fix-slash-commands.cjs` and that requiring `command-roster` / loading `gsd-tools` does not throw.

**Acceptance criteria:**
- [ ] After a clean `install()` into a temp config dir, `<configDir>/scripts/fix-slash-commands.cjs` exists.
- [ ] `node <configDir>/gsd-core/bin/gsd-tools.cjs query init.new-project` exits 0 and prints JSON (no `MODULE_NOT_FOUND`).
- [ ] A smoke/tarball assertion fails if `scripts/fix-slash-commands.cjs` is missing from the install (regression guard mirroring #935/#606).
- [ ] `readCmdNames()` returns `[]` (does not throw) when `commands/gsd` is absent; unchanged when it exists.
- [ ] Uninstall removes the copied `scripts/fix-slash-commands.cjs`.
- [ ] Regression proof: a test reproduces the `MODULE_NOT_FOUND` load failure against a manifest missing the file before the fix, and passes after.

**Out of scope:**
- Refactoring the command-roster require chain or the `../../../scripts/` relative-path convention.
- Other missing-file classes beyond `fix-slash-commands.cjs` (open a separate issue if found).

**Contribution requirements (this repo):**
- No bot branch exists yet — create `fix/1223-installer-fix-slash-commands-missing` (per `RULESET.CONTRIB.BRANCH.format`; the `claude/` prefix is rejected by the branch-naming gate).
- PR body must contain `Closes #1223`.
- Add a typed `Fixed` changeset fragment (`pr:0` placeholder, backfill after the PR number is known); do **not** edit `CHANGELOG.md`. `Fixed` is docs-exempt.
- Regression-test-first; `gsd-test-summary` docker green (exit 0) before push. This is exactly the "fresh installs tested, never upgrades" CI gap noted in #670 — exercise a real install in the test, not just a unit of the manifest builder.

**Comment by pograinger** [comment]
## Regressed in 1.11.0 — verbatim, plus a second instance this issue did not cover

This reproduces exactly as filed, on a fresh global install of **1.11.0** (Claude Code runtime, Linux x86_64, Node v22.23.2).

```
Error: Cannot find module '../../../scripts/fix-slash-commands.cjs'
Require stack:
- ~/.claude/gsd-core/bin/lib/command-roster.cjs
- ~/.claude/gsd-core/bin/lib/runtime-artifact-conversion.cjs
- ~/.claude/gsd-core/bin/lib/install-profiles.cjs
- ~/.claude/gsd-core/bin/lib/runtime-artifact-layout.cjs
- ~/.claude/gsd-core/bin/lib/installed-surface-resolver.cjs
- ~/.claude/gsd-core/bin/lib/install-shadow-report.cjs
- ~/.claude/gsd-core/bin/lib/health-diagnostic-rules/install-surface-shadowing.cjs
- ~/.claude/gsd-core/bin/lib/health-diagnostic.cjs
- ~/.claude/gsd-core/bin/lib/verify.cjs
- ~/.claude/gsd-core/bin/lib/phase.cjs
- ~/.claude/gsd-core/bin/gsd-tools.cjs
  code: 'MODULE_NOT_FOUND'
```

The intermediate modules differ from the original report, but the head and tail are identical, and the effect is the same: the throw is at **module load** of a dependency in the `gsd-tools.cjs` require chain, so every `gsd_run query …` fails and no workflow can run. `/gsd-resume-work` aborts before its first query.

### The package is fine; the installer is not

`package.json` `files` **does** include `scripts`, and the published tarball contains **120** files under `package/scripts/`, including `fix-slash-commands.cjs`. But the installed runtime home has no `scripts/` directory at all:

```
$ ls ~/.claude/gsd-core/
VERSION  bin  contexts  references  templates  workflows
```

So this is specifically the step that populates the runtime home, not packaging.

### A second instance, which this issue did not cover

I audited **every** relative `require()` in the installed tree — 865 of them, after stripping comments (an unstripped pass produced 7 false positives, all matches inside doc comments). **Exactly two** are unresolvable, and both reach out of the shipped `gsd-core/` tree into `scripts/`:

| module | requires | behavior |
|---|---|---|
| `bin/lib/command-roster.cjs` | `../../../scripts/fix-slash-commands.cjs` | **eager** — hard-fails every `gsd-tools` invocation |
| `bin/lib/capability-loader.cjs` | `../../../scripts/gen-capability-registry.cjs` | **lazy** (inside `getGenerator()`) — silent until an overlay candidate exists |

The second one is why I'm flagging it: it is the same defect, but it fails only on a specific path, so it will not be caught by "does the CLI start". Fixing only the eager one leaves it in place — which is what I did first, and I found the second only by auditing rather than by hitting it.

### Same class as #2071, and that issue already prescribes the fix

`bin/lib/install-effort-resolver.cjs` documents the precedent in its own header:

> It previously reached those two functions via `require('../../../bin/install.js')`, but the installer never copies the package-root `bin/install.js` into a runtime home, so `effort sync` crashed with MODULE_NOT_FOUND in every installed runtime (#2071). Moving the logic here — a `src/*.cts` module compiled into the shipped `gsd-core/bin/lib/` tree — lets both the installer AND `effort sync` require it from a location that is always present.

That remedy — move the logic into the shipped tree rather than copy the file — would close both remaining cases structurally. A guard test asserting that no module under `gsd-core/bin/lib/` resolves a require outside `gsd-core/` would keep the class closed; there are only two violations today.

### Workaround

Extracting the two files from the version-matched tarball into `~/.claude/scripts/` restores `gsd-tools` (`rc=1` → `rc=0`):

```bash
npm pack @opengsd/gsd-core@1.11.0
tar xzf opengsd-gsd-core-1.11.0.tgz \
  package/scripts/fix-slash-commands.cjs \
  package/scripts/gen-capability-registry.cjs
mkdir -p ~/.claude/scripts && cp package/scripts/*.cjs ~/.claude/scripts/
```

### Not verified

I did not test other runtimes (Cursor, Codex, Gemini, …) or a non-global install, so I can't say whether the omission is specific to the Claude Code global-install path.

**Comment by pograinger** [comment]
## A guard that would close this class — implementation, with its controls

Following up on the regression report above. The remedy #2071 already prescribes is *move the logic into the shipped tree*; the missing half is something that **notices when a module stops obeying that**. Here is a working check — MIT-equivalent, do whatever you like with it.

The property it tests is deliberately **not** "does the target file exist". It is **"does any module shipped inside `gsd-core/` resolve a relative require that escapes `gsd-core/`"**. Existence is host-dependent and passes in the repo; the boundary is the thing that actually differs between your checkout and an installed runtime home.

```js
/** Strip line/block comments and string literals, so only real code remains. */
function stripNonCode(src) {
  let out = '', i = 0, n = src.length;
  while (i < n) {
    const c = src[i], d = src[i + 1];
    if (c === '/' && d === '/') { while (i < n && src[i] !== '\n') i++; continue; }
    if (c === '/' && d === '*') { i += 2; while (i < n && !(src[i] === '*' && src[i + 1] === '/')) i++; i += 2; continue; }
    if (c === '"' || c === "'" || c === '`') {
      const q = c; out += c; i++;
      while (i < n && src[i] !== q) { if (src[i] === '\\') { out += src[i]; i++; } out += src[i]; i++; }
      out += q; i++; continue;
    }
    out += c; i++;
  }
  return out;
}

function findViolations(shippedRoot) {
  const root = path.resolve(shippedRoot);
  const re = /require\(\s*['"](\.[^'"]+)['"]\s*\)/g;
  const violations = [];
  for (const file of walk(root)) {                 // walk = recursive *.cjs/*.js
    const code = stripNonCode(fs.readFileSync(file, 'utf8'));
    for (const m of code.matchAll(re)) {
      const target = path.resolve(path.dirname(file), m[1]);
      if (!(target + path.sep).startsWith(root + path.sep) && target !== root) {
        violations.push({ file: path.relative(root, file), specifier: m[1] });
      }
    }
  }
  return violations;
}
```

### ⚠️ Comment-stripping is load-bearing, not tidiness

An **unstripped** pass over the 1.11.0 tree reports **7 violations and all 7 are `require(...)` occurrences inside doc comments** — including three that are prose *about this very bug class* (`install-effort-resolver.cjs:13`, `runtime-artifact-conversion.cjs:53`, `runtime-hooks-surface.cjs:26`). A guard without stripping reports your own documentation of #2071 as a fresh instance of #2071. I hit that on my first pass.

### Controls I ran

| control | expectation | result |
|---|---|---|
| **positive** — 1.11.0 install tree | finds the 2 real ones | ✅ exactly `command-roster.cjs` and `capability-loader.cjs`, no comment hits |
| **discriminating** — after copying the 2 files into `~/.claude/scripts/` | **still fails**, because copying does not fix the boundary | ✅ still 2 |
| **negative** — synthetic tree with only in-tree requires | clean | ✅ `rc=0` |

The discriminating control is the one I would keep: it distinguishes the real remedy (move the logic) from the workaround (copy the file), so the guard cannot be satisfied by papering over the symptom.

### Current output on 1.11.0

```
require-boundary: 2 module(s) require outside the shipped tree:
  bin/lib/capability-loader.cjs  ->  ../../../scripts/gen-capability-registry.cjs
  bin/lib/command-roster.cjs     ->  ../../../scripts/fix-slash-commands.cjs
```

Two violations total, so this can go green in one change rather than arriving as a backlog.

### Not verified

I have not run it against your source tree (`src/*.cts` pre-compile) — only the shipped `gsd-core/` output. The regex catches static `require()` only; a computed or `createRequire` specifier would slip past it. Both seemed acceptable for a boundary guard whose job is to catch the accidental case, but worth stating rather than leaving you to discover.
