### PR TITLE
fix(#1223): install scripts/fix-slash-commands.cjs so gsd-tools loads

### LINKED ISSUE #1223: bug(installer): gsd-tools CLI crashes at load — scripts/fix-slash-commands.cjs missing from install, every gsd_run fails (regression since 1.5.0-rc.1)
### Pre-submission

- [x] I have searched existing issues and this bug has not already been reported. (Searched: `fix-slash-commands`, `command-roster`, `MODULE_NOT_FOUND`, "cannot find module", "install scripts missing", `init.new-project`. Closest relatives are #935 and #606 — same *installer-omits-a-required-file* family, but a different file; none cover `scripts/fix-slash-commands.cjs`.)

### GSD Version

`1.5.0-rc.3` (from `~/.claude/gsd-core/VERSION`)

### Runtime

Claude Code

### Operating System

macOS (Darwin 25.6.0, Apple Silicon)

### Node.js Version

`v26.0.0`

### Installation Method

Global install into `~/.claude` (updated/reinstalled to `1.5.0-rc.3`).

### What happened?

**Every** GSD command that shells out to the `gsd-tools` CLI crashes at module-load time, so no workflow can run. I hit it on `/gsd-new-project`, which aborts at Step 1 (Setup) on its first `gsd_run query init.new-project` call:

```
Error: Cannot find module '../../../scripts/fix-slash-commands.cjs'
Require stack:
- ~/.claude/gsd-core/bin/lib/command-roster.cjs
- ~/.claude/gsd-core/bin/lib/runtime-artifact-conversion.cjs
- ~/.claude/gsd-core/bin/lib/runtime-artifact-layout.cjs
- ~/.claude/gsd-core/bin/lib/surface.cjs
- ~/.claude/gsd-core/bin/lib/capability-state.cjs
- ~/.claude/gsd-core/bin/lib/loop-resolver.cjs
- ~/.claude/gsd-core/bin/gsd-tools.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1475:15)
  code: 'MODULE_NOT_FOUND'
```

Because the throw is at **module load** of a core dependency in the `gsd-tools.cjs` require chain, it is not specific to `new-project` — any `gsd_run query …` (config, commit, state, roadmap, plan, etc.) fails identically. `/gsd-new-project` wrote nothing (no `.planning/` created), so at least the failure is clean.

### What did you expect?

`node ~/.claude/gsd-core/bin/gsd-tools.cjs query init.new-project` should load and emit JSON, and `/gsd-new-project` should proceed past Step 1.

### Steps to reproduce

1. Install/update GSD `1.5.0-rc.3` globally into `~/.claude` (Claude Code runtime).
2. Run any GSD workflow, e.g. `/gsd-new-project`, or invoke the CLI directly:
   ```
   node ~/.claude/gsd-core/bin/gsd-tools.cjs query init.new-project
   ```
3. Observe the `MODULE_NOT_FOUND` crash above.

### How often does this happen?

Every time.

### Impact

Blocker — the entire CLI is unusable; no GSD command can run.

### Error output / logs

See the require-stack trace above.

### Root cause analysis

`bin/lib/command-roster.cjs` (compiled from `src/command-roster.cts`) does, at line 9:

```js
const slashCommandTransformer = require('../../../scripts/fix-slash-commands.cjs');
```

From the installed location `~/.claude/gsd-core/bin/lib/command-roster.cjs`, `../../../scripts/` resolves to **`~/.claude/scripts/fix-slash-commands.cjs`** (i.e. `scripts/` is expected to be a *sibling of* `gsd-core/`, not inside it — which matches the repo dev layout where `gsd-core/` and `scripts/` are siblings at repo root).

On this install:

- `~/.claude/scripts/` **exists** and contains `changeset/` and `lib/`.
- `~/.claude/scripts/fix-slash-commands.cjs` **does not exist**.
- There is **no** `scripts/` directory inside `~/.claude/gsd-core/` either (only `bin contexts references templates workflows VERSION`).

So the installer's copy manifest deploys part of `scripts/` (e.g. `scripts/changeset/…`, cf. #935) but **omits the top-level file `scripts/fix-slash-commands.cjs`** that `command-roster.cjs` hard-requires at load. In the repo this file lives at `scripts/fix-slash-commands.cjs` and is depended on by `src/command-roster.cts` plus several tests (`tests/bug-2543-*`, `bug-2808-*`, `bug-3677-*`, `bug-3683-*`), so it is a shipped runtime dependency, not test-only.

This is the same defect class as:
- #935 — `scripts/changeset/cli.cjs` not installed (+ wrong path)
- #606 — installer does not copy `hooks/managed-hooks-registry.cjs`, crashing the update checker

Suggested fix direction (for maintainers): add `scripts/fix-slash-commands.cjs` to the installer copy manifest so it lands where `command-roster.cjs`'s `../../../scripts/` require resolves (`~/.claude/scripts/fix-slash-commands.cjs`), with a release-tarball/smoke assertion that the file is present and `gsd-tools query` loads — mirroring the guards added for #935/#606.

### Regression window

This is a **regression**: GSD worked fine on `1.5.0-rc.1`. It is broken on `1.5.0-rc.3`. `1.5.0-rc.2` was not tested, so the break was introduced in **rc.2 or rc.3** — likely a change to the installer copy manifest or to the `command-roster.cjs` require path in that window. (Possibly related: #1099 "Extract runtime artifact conversion module" introduced `runtime-artifact-conversion.cjs`, which sits in this require chain.)

I have **not** verified whether the current stable release is affected — I briefly switched to it only to get the tools to install, then reinstalled rc.3 *before* testing, so stable is untested here.

### Privacy

- [x] I have reviewed for PII and redacted absolute home paths to `~`. No tokens, keys, or credentials are included.

### PR DESCRIPTION
**Pull request by jslitzkerttcu**
## Linked Issue

Fixes #1223

> Linked issue carries `confirmed-bug` (and `priority: high`, `ready-for-agent`).

---

## What was broken

Every `gsd-tools` invocation crashed at module load with `Cannot find module '../../../scripts/fix-slash-commands.cjs'` on installed runtimes (regression since 1.5.0-rc.1), so no GSD workflow could run.

## What this fix does

The installer now copies `scripts/fix-slash-commands.cjs` into `<install-root>/scripts/` (where `command-roster` requires it), tracks it in the file manifest, and removes it on uninstall. `readCmdNames()` also degrades to `[]` when no `commands/gsd` directory exists.

## Root cause

`gsd-core/bin/lib/command-roster.cjs` hard-requires `../../../scripts/fix-slash-commands.cjs` at module load, resolving to `<install-root>/scripts/fix-slash-commands.cjs` (a sibling of `gsd-core/`). The file ships in the npm tarball root but the installer copy manifest deployed `scripts/changeset/` and `scripts/lib/` while omitting this top-level file. Because the throw is at load of a core dependency in the `gsd-tools` require chain, every `gsd_run query ...` failed identically. Same defect class as #935 (`scripts/changeset/cli.cjs`) and #606 (`hooks/managed-hooks-registry.cjs`).

A second, latent failure: `readCmdNames()` did an unguarded `fs.readdirSync(commands/gsd)`, which throws `ENOENT` on skill-based installs lacking that directory — now guarded.

### How I verified the fix

Added regression guards in `tests/install.test.cjs` that drive a real `install()` into a temp config dir and assert:
- `scripts/fix-slash-commands.cjs` lands at `<configDir>/scripts/`
- the installed `gsd-tools query init.new-project` exits 0, emits valid JSON, and produces no `MODULE_NOT_FOUND`
- requiring the installed `command-roster.cjs` resolves cleanly
- the manifest tracks the file and `uninstall()` removes it
- `readCmdNames()` returns `[]` when `commands/gsd` is absent

All 123 install tests pass; the namespace-transformer suites that consume the module (bug-2543/2808/3683/3677) stay green.

### Regression test added?

- [x] Yes — added a test that would have caught this bug
- [ ] No

### Platforms tested

- [ ] macOS
- [x] Windows (including backslash path handling)
- [ ] Linux
- [ ] N/A

### Runtimes tested

- [x] Claude Code
- [ ] Gemini CLI
- [ ] OpenCode
- [ ] N/A

---

## Checklist

- [x] Issue linked above with `Fixes #1223`
- [x] Linked issue has the `confirmed-bug` label
- [x] Fix is scoped to the reported bug — no unrelated changes included
- [x] Regression test added
- [x] All existing tests pass (`npm test`)
- [x] `.changeset/` fragment added (`Fixed`)
- [x] No unnecessary dependencies added

## Breaking changes

None

---
<a href="https://app.blacksmith.sh/open-gsd/codesmith/gsd-core/pr/1232"><picture><source media="(prefers-color-scheme: dark)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/view-with-codesmith-dark-v2.svg"><source media="(prefers-color-scheme: light)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/view-with-codesmith-light-v2.svg">View with Codesmith</picture></a> <a href="https://backend.blacksmith.sh/track/enable-autofix?expires=1784053693&installation_id=134682257&pr_number=1232&repository=open-gsd%2Fgsd-core&return_to=https%3A%2F%2Fgithub.com%2Fopen-gsd%2Fgsd-core%2Fpull%2F1232&signature=d549f64413361b78766065f9180890c14b98d67be7eeb3ffaa8c38e58fc701c8"><picture><source media="(prefers-color-scheme: dark)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/autofix-with-codesmith-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/autofix-with-codesmith-light.svg">Autofix with Codesmith</picture></a>
<sup>Need help on this PR? Tag <code>/codesmith</code> with what you need. Autofix is disabled.</sup>

### CODE REVIEW

**Review by trek-e — COMMENTED** [review]
## Review: superseded by the already-merged #1240

### Summary

This PR correctly diagnoses and fixes a real, high-priority blocker (issue #1223 — the installer never copied `scripts/fix-slash-commands.cjs`, so `command-roster.cjs`'s load-time `require('../../../scripts/fix-slash-commands.cjs')` threw `MODULE_NOT_FOUND` and every `gsd-tools` invocation died). The diagnosis is accurate and the fix targets the true root cause.

**However, the same fix for #1223 has already landed on `next` via the merged [#1240](https://github.com/open-gsd/gsd-core/pull/1240)** (merge commit `00acbc886`, merged 2026-06-14 20:03 UTC), which **closed #1223** (`stateReason: completed`). That merge is *why this PR now shows `CONFLICTING`* — `next` already carries an overlapping change to the same three files. As a result this PR is a duplicate with nothing left to merge, and on one dimension it would regress `next` if it were force-merged. Recommendation: **close as superseded** (details + credit below).

I deliberately did **not** run the full `/security-review` · `/codex:adversarial-review` · `/code-review` gate battery here: the equivalent (and on one point stronger) code is already merged on `next`, so exercising those gates against dead duplicate code would be wasted effort. I instead compared this diff line-for-line against what #1240 already shipped.

### Classification & gate compliance (bug-fix track)

- **`RULESET.CONTRIB.CLASSIFY.fix=requires confirmed/confirmed-bug before implementation`** — ✅ #1223 carries `confirmed-bug` (+ `priority: high`, `ready-for-agent`).
- **`CI.GATE.issue-link-required`** — ✅ body has `Fixes #1223`; commits carry `Closes #1223`.
- **Branch / commits / changeset / template** — all ✅ well-formed: `fix/1223-installer-fix-slash-commands-missing`, conventional commit subjects, a `type: Fixed` changeset fragment (`Fixed` is docs-exempt under `RULESET.PR-FLOW.docs-by-changeset-type`), and the Fix-PR template is followed. **The PR is clean on format — the only problem is that it is a duplicate of merged work.**

### Root-cause & paper-over verdict

- **Root cause is correct and not papered over.** `src/command-roster.cts:11` does a top-level (load-time) `require('../../../scripts/fix-slash-commands.cjs')` which resolves to `<install-root>/scripts/fix-slash-commands.cjs`; the installer shipped `scripts/changeset/` + `scripts/lib/` but omitted this top-level file. The fix copies the file to where the `require` resolves, tracks it in the manifest, and removes it on uninstall — it fixes the installer's copy manifest at the true defect site, not the symptom. Same defect family as #935 / #606. ✅ Passes the anti-paper-over gate.
- **Regression discipline** — ✅ the added `tests/install.test.cjs` guards drive a real `install()` and assert the file lands, `gsd-tools query` loads with no `MODULE_NOT_FOUND` and exits 0 with valid JSON, the manifest tracks it, and `uninstall()` removes it. These would have failed on the pre-fix base.

### Side-by-side vs the merged #1240

| Dimension | This PR (#1232) | Merged #1240 (on `next`) | Winner |
|---|---|---|---|
| Installer copy + manifest + uninstall (`bin/install.js`) | copies file, `verifyFileInstalled`, manifest entry, uninstall unlink | functionally equivalent (self-contained copy block, same verify/manifest/uninstall) | **tie** |
| `readCmdNames()` guard | `try { … } catch { return []; }` — swallows **all** errors (ENOENT *and* EACCES/ENOTDIR) | swallows **only** `ENOENT`; `if (err.code !== 'ENOENT') throw err` with a comment on why real misconfig must propagate | **#1240** |
| Cursor `/gsd:`→`gsd-` rewrite exemption (`bug-376` Suite 2b) | `if (path.basename(rel) === 'fix-slash-commands.cjs') continue;` | `INFRA_BASENAMES = new Set(['fix-slash-commands.cjs'])` + membership check (extensible) | tie (both correct; #1240 marginally cleaner) |
| Regression tests | install/load/manifest/uninstall + readCmdNames | same coverage, already green on `next` | tie |
| Mergeability | **CONFLICTING** | merged | **#1240** |

**Net:** #1240 ties this PR on the installer fix, the test exemption, and the regression coverage, and **wins** on `readCmdNames` error handling — its version rethrows non-`ENOENT` errors (e.g. `EACCES`, `ENOTDIR`) instead of silently returning an empty roster, so a real misconfiguration can't masquerade as "no commands." This PR's catch-all is the weaker shape; force-merging it would *regress* that handling on `next`. There is nothing in this PR that isn't already present on `next` in an equal-or-better form.

### Findings by severity

- **Blocker (moot — only if merged):** the `readCmdNames` catch-all swallows `EACCES`/`ENOTDIR`, regressing the `ENOENT`-only guard already on `next`. Not actionable here because the PR is superseded.
- **Major:** Duplicate of the merged #1240; #1223 is already closed/completed. No mergeable delta remains.
- **Major:** `CONFLICTING` against `next` (overlaps #1240's merged changes).

### Credit where due

To be explicit, because the merged PR doesn't capture it: **@jslitzkerttcu filed #1223 with an unusually precise root-cause analysis** — pinpointing the `command-roster.cjs` load-time require, the `../../../scripts/` resolution to a sibling of `gsd-core/`, the missing top-level file, the #935/#606 defect family, and the rc.1→rc.3 regression window. That analysis is the backbone of the fix that shipped. This PR was also the **first-mover** (opened ~75 min before #1240) and independently identified the non-obvious need to exempt the transformer module from the Cursor rewrite scan. Thank you — the diagnosis directly enabled the resolution.

### Verdict

**Recommend closing as superseded by the merged #1240** — the fix for #1223 is already live on `next` in an equivalent-or-stronger form. No code change is needed here.

**Comment by trek-e** [comment]
Closing as superseded by #1240, which fixed #1223 with an equivalent installer copy — plus a slightly stronger `readCmdNames` guard that rethrows non-`ENOENT` errors instead of swallowing them — and is already merged to `next` (which is also why this branch now shows as conflicting). Full side-by-side in my review above.

Thank you @jslitzkerttcu — your #1223 root-cause analysis (the load-time `command-roster` require resolving to the missing top-level `scripts/fix-slash-commands.cjs`, the #935/#606 defect family, the rc.1→rc.3 regression window) is exactly what the shipped fix is built on, and this was the first-mover PR on the bug. Much appreciated.
