### PR TITLE
fix(#725): route Codex gsd-tools calls through shim

### LINKED ISSUE #725: bug(codex): generated skills and agents can call bare gsd-tools on shim-only installs
## Summary

Codex installs can be shim-only: `~/.codex/gsd-core/bin/gsd-tools.cjs` exists, but there is no bare `gsd-tools` binary on `PATH`. Several generated Codex skill/agent surfaces still instruct the agent to run command-position `gsd-tools ...` invocations, so the workflow can fail with `gsd-tools: command not found` and then silently continue by bypassing GSD ceremony.

This is related to #619/#637/#705, but the affected surface is the Codex install output generated from `commands/gsd/*.md` and `agents/*.md`, not just workflow shell blocks or hardcoded `$HOME/.claude/...gsd-tools.cjs` paths.

## Reproduction

On a Codex global install where `~/.codex/gsd-core/bin/gsd-tools.cjs` exists but `gsd-tools` is not on `PATH`:

```bash
which -a gsd-tools || true
ls -l ~/.codex/gsd-core/bin/gsd-tools.cjs
rg -n '(^|[$(`;&|])\s*gsd-tools\s' ~/.codex/skills ~/.codex/agents
```

A concrete observed failure while running a quick task:

```text
Ran gsd-tools query init.quick --help
  /usr/bin/bash: line 1: gsd-tools: command not found
```

Representative installed skill output before the fix:

```markdown
# ~/.codex/skills/gsd-quick/SKILL.md

gsd-tools query frontmatter.get .planning/quick/{dir}/SUMMARY.md status
...
gsd-tools query init.quick
```

Representative source agent examples before the fix include command-position `gsd-tools query ...` in `agents/gsd-planner.md`, `agents/gsd-executor.md`, `agents/gsd-plan-checker.md`, `agents/gsd-verifier.md`, etc.

## Expected

Codex-generated SKILL.md and agent TOML should not depend on a bare `gsd-tools` executable. They should either:

- invoke the Codex-local shim directly, e.g. `node "$HOME/.codex/gsd-core/bin/gsd-tools.cjs" query ...`, or
- route through a runtime resolver that can find the Codex shim.

Workflow launchers used by Codex-installed workflow files should also be able to find `$HOME/.codex/gsd-core/bin/gsd-tools.cjs` when no project-local runtime and no PATH binary exist.

## Suggested fix

1. In the Codex markdown converter, rewrite command-position bare `gsd-tools ...` forms to `node "$HOME/.codex/gsd-core/bin/gsd-tools.cjs" ...` while preserving resolver probes such as `command -v gsd-tools`.
2. Add `.codex/gsd-core/bin/${_GSD_SHIM_NAME}` fallback arms to the canonical runtime launcher, then propagate it with `scripts/sync-runtime-launcher.cjs`.
3. Add regression tests over:
   - `convertClaudeCommandToCodexSkill()`
   - `convertClaudeAgentToCodexAgent()` / generated agent TOML
   - installed Codex skills under a temp `CODEX_HOME`
   - `gsd_run` resolving `$HOME/.codex/gsd-core/bin/gsd-tools.cjs` with no `gsd-tools` on PATH

## Local verification from a downstream fix

```bash
npm run build:lib
node --test tests/codex-config.test.cjs \
  tests/bug-3582-codex-skills-materialized.test.cjs \
  tests/runtime-launcher-parity.test.cjs \
  tests/bug-211-launcher-home-fallback.test.cjs \
  tests/bug-444-resolver-local-claude-install.test.cjs \
  tests/bug-2851-workflow-bare-gsd-tools.test.cjs
```

Result: 138 tests passed.

## Impact

Moderate. GSD workflows appear to run, but important init/state/commit helpers can be skipped or replaced by manual shortcuts when Codex agents hit `gsd-tools: command not found`.

### PR DESCRIPTION
**Pull request by j2h4u**
## Fix PR

> **Using the wrong template?**
> — Enhancement: use [enhancement.md](?template=enhancement.md)
> — Feature: use [feature.md](?template=feature.md)

---

## Linked Issue

Fixes #725

---

## What was broken

Generated Codex skills and agent TOML could still ask agents to execute bare `gsd-tools` commands. Shim-only Codex installs materialize `$gsd-*` skills under `~/.codex`, but they do not guarantee a `gsd-tools` binary on `PATH`, so those generated calls could fail with `command not found`.

## What this fix does

Codex markdown conversion now rewrites command-position bare `gsd-tools` invocations to `node "$HOME/.codex/gsd-core/bin/gsd-tools.cjs"` while preserving resolver probes such as `command -v gsd-tools`. The shared runtime launcher also probes repo-local and home-local `.codex/gsd-core/bin/gsd-tools.cjs` fallbacks, and the launcher snippet is re-synced across workflow files.

This is a conflict-free branch based on current `next`; related PR #731 is currently `CONFLICTING`.

## Root cause

The installer converted Claude paths to Codex paths, but it did not normalize command-position `gsd-tools` references in generated Codex surfaces. The shared launcher also only had `.claude` local/home fallback arms plus the optional `PATH` binary, leaving Codex shim-only installs without a local fallback path.

### How I verified the fix

- `npm ci --ignore-scripts --no-audit --no-fund`
- `npm run build:lib`
- `git diff --check`
- `node scripts/changeset/lint.cjs`
- `node --test tests/codex-config.test.cjs tests/bug-3582-codex-skills-materialized.test.cjs tests/runtime-launcher-parity.test.cjs` — 150 passed
- `node --test tests/roadmap.test.cjs` — 32 passed after full-suite failure triage
- Baseline check: `tests/roadmap.test.cjs` also passes on clean `upstream/next` at `29c0a2f5`
- `npm test` was attempted; it failed once in `tests/roadmap.test.cjs` with `planningPaths is not a function`. The same file passes in isolation on this branch and on clean `upstream/next`, so I am treating it as an existing order-dependent full-suite isolation issue rather than part of this Codex shim fix.

### Regression test added?

- [x] Yes — added tests covering generated Codex skill/agent surfaces and launcher fallback behavior
- [ ] No — explain why: 

### Platforms tested

- [ ] macOS
- [ ] Windows (including backslash path handling)
- [x] Linux
- [ ] N/A (not platform-specific)

### Runtimes tested

- [ ] Claude Code
- [ ] Gemini CLI
- [ ] OpenCode
- [x] Other: Codex
- [ ] N/A (not runtime-specific)

---

## Checklist

- [x] Issue linked above with `Fixes #NNN` — **PR will be auto-closed if missing**
- [x] Linked issue has the `confirmed-bug` label
- [x] Fix is scoped to the reported bug — no unrelated changes included
- [x] Regression test added (or explained why not)
- [ ] All existing tests pass (`npm test`)
- [x] `.changeset/` fragment added if this is a user-facing fix (`npm run changeset -- --type Fixed --pr <NNN> --body "..."`) — or `no-changelog` label applied
- [x] No unnecessary dependencies added

## Breaking changes

None

---
<a href="https://app.blacksmith.sh/open-gsd/codesmith/gsd-core/pr/855"><picture><source media="(prefers-color-scheme: dark)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/view-with-codesmith-dark-v2.svg"><source media="(prefers-color-scheme: light)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/view-with-codesmith-light-v2.svg">View with Codesmith</picture></a> <a href="https://backend.blacksmith.sh/track/enable-autofix?expires=1783495069&installation_id=134682257&pr_number=855&repository=open-gsd%2Fgsd-core&return_to=https%3A%2F%2Fgithub.com%2Fopen-gsd%2Fgsd-core%2Fpull%2F855&signature=1bc29e064b805cc60c22727b303351dd4c8ab59ab61317c962c70f5976b3e3ee"><picture><source media="(prefers-color-scheme: dark)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/autofix-with-codesmith-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/autofix-with-codesmith-light.svg">Autofix with Codesmith</picture></a>
<sup>Need help on this PR? Tag <code>/codesmith</code> with what you need. Autofix is disabled.</sup>

### CODE REVIEW

**Review by trek-e — COMMENTED** [review]
## Summary

`fix(#725)` routes Codex-generated `SKILL.md` / agent-TOML bare `gsd-tools` calls through the home-local shim and adds `.codex/gsd-core/bin/` fallback arms to the runtime launcher, re-synced across the workflow files. **Bug-Fix Track** — issue #725 carries `confirmed-bug`. Reviewed per the gsd-core PR review directive and verified in an isolated checkout with base-vs-PR test runs.

## Classification & gate compliance

- Linked issue: ✅ `Fixes #725` + `confirmed-bug` → Bug-Fix Track (`RULESET.CONTRIB.CLASSIFY.fix=requires confirmed/confirmed-bug before implementation`).
- Branch `fix/725-codex-gsd-tools-shim-conflict-free` ✅ matches `fix/NNN-slug`.
- Commit `fix(#725): …` ✅ conventional.
- Changeset `.changeset/725-codex-gsd-tools-shim.md` ✅ `type: Fixed`, valid frontmatter+body; `Fixed` → docs gate exempt ✅.
- One concern ✅ — the ~80 workflow-file edits are mechanical launcher re-sync (verified: only the snippet line changed in sampled files), not scope creep.

## Root-cause & paper-over verdict: **PASS**

`rewriteBareGsdToolsCommandsForCodex` (`bin/install.js` ~3014) rewrites command-position bare `gsd-tools` — line-start, `$( … )`, backtick, and after `&& || ; |` — to `node "$HOME/.codex/gsd-core/bin/gsd-tools.cjs"`, and **preserves** resolver probes. Verified by live evaluation: `command -v gsd-tools`, `which gsd-tools`, `type gsd-tools`, and identifier substrings (`my_gsd-tools_var`) are untouched. The launcher snippet adds repo-local + `$HOME`-local `.codex` arms alongside the existing `.claude` arms while keeping the PATH probe. This corrects behavior at the root cause (generation **and** resolution) — no output suppression, no error swallowing, no test-input special-casing.

## Fail-first regression proof: **PASS** (all three modified test files)

Each test run on the PR branch (pass) and against base code with the PR's test file applied (fail):

| Test file | PR | Base | Base failure |
|---|---|---|---|
| `runtime-launcher-parity` | 8/8 ✅ | 7/8 ❌ | `snippet.sh must contain the Codex fallback arm (".codex/gsd-core/bin/")` (line 403) |
| `codex-config` | 136/136 ✅ | 133/136 ❌ | rewrites command-substitution / line-start; `gsd-code-fixer.toml must not contain a command-position bare gsd-tools` |
| `bug-3582-codex-skills-materialized` | 6/6 ✅ | 5/6 ❌ | `gsd-autonomous/SKILL.md must not contain a command-position bare gsd-tools` |

Launcher parity holds (parity test green; sampled workflow files show only the snippet line changed).

## Findings by severity

**Minor**
1. `RULESET.TESTS.property-based-testing` — the converter is a text-transformation contract; the standard asks for ≥1 `fast-check` property test. The four regex branches are well covered by enumerated cases (including the critical probe-preservation cases), but a property test over fuzzed content would guard against future regex interactions. Recommend adding one.
2. CONTEXT.md `### Runtime Launcher Module` (line 68) describes the chain as "node when present, falls back to a `gsd-tools` binary on PATH, else errors" — it now omits the per-runtime (`.claude` / `.codex`) home fallback arms. It was already non-exhaustive (never enumerated the `.claude` arms), so this is not a hard gate violation, but a one-line update mentioning multi-runtime home fallbacks would keep the seam description accurate.

**Nit**
3. `rewriteBareGsdToolsCommandsForCodex` is not exported; it's covered indirectly via the two converters. A direct export would enable isolated unit + property testing (ties to finding 1).

## Verdict: **Comment** (no blockers)

Correct, root-cause fix with a solid fail-first proof and clean format. The items above are quality/precision improvements, not merge blockers. Nice work on the probe-preservation regex — that's the part most likely to regress and it's well guarded.

**Comment by j2h4u** [comment]
Pushed the requested follow-up: the Codex gsd-tools rewrite helper is exported and covered with property tests, and CONTEXT.md now documents the Claude/Codex/OpenCode home-fallback shim behavior.

**Comment by jeremymcs** [comment]
duplicate of #731
