### ISSUE TITLE
bug: ci-smoke-skip.cjs Node port fails with MODULE_NOT_FOUND — Skip step runs before actions/checkout (PR #434 regression)

### ISSUE THREAD

**Issue by trek-e** [open-gsd/gsd-core#439]
## GSD Version

1.2.0-rc.2 (CI infrastructure; not a user-facing version regression)

## Runtime

Multiple (specify in description)

## Operating System

Linux (Ubuntu/Debian)

## Node.js Version

v22.x / v24.x (both affected)

## Shell

bash

## Installation Method

npx @opengsd/get-shit-done-redux@latest (fresh run)

## What happened?

The `Skip full-only matrix entry on PR` step in `.github/workflows/install-smoke.yml` (smoke job) calls `node scripts/ci-smoke-skip.cjs`, but the step is positioned BEFORE `actions/checkout@v4`. The workspace is empty at that point, so Node fails with `Cannot find module '/home/runner/work/.../scripts/ci-smoke-skip.cjs'` (exit 1). Every smoke job fails at step 2 since PR #437's parse fix actually let the workflow execute.

PR #434 ported the original inline bash Skip step to `node scripts/ci-smoke-skip.cjs`. The bash inline didn't depend on any file existing — it just read env vars and wrote to `$GITHUB_OUTPUT`. The Node port requires the script file in workspace, which requires checkout. The Skip step is positioned before checkout as an optimization (skip fast without paying checkout cost on PRs).

PR #438 run https://github.com/open-gsd/get-shit-done-redux/actions/runs/26580199043 — both `smoke (ubuntu-latest, 22, false, bash)` and `smoke (ubuntu-latest, 24, true, bash)` fail at step 2 in 3–8 seconds (no time for checkout to complete).

## What did you expect?

Either (a) the Skip step should use inline shell that reads only env vars + `$GITHUB_OUTPUT` (no file dependency), preserving the pre-checkout fast-exit behavior, OR (b) the Skip step is moved after checkout (loses the optimization but simpler). Either way, smoke jobs should not fail at step 2.

## Steps to reproduce

1. Open a PR against `next` that triggers `install-smoke.yml`
2. Observe `smoke (ubuntu-latest, 22, false, bash)` and `smoke (ubuntu-latest, 24, true, bash)` fail within 3–8 seconds at step 2 (`Skip full-only matrix entry on PR`)

## Error output / logs

```
Error: Cannot find module '/home/runner/work/get-shit-done-redux/get-shit-done-redux/scripts/ci-smoke-skip.cjs'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1430:15)
    ...
  code: 'MODULE_NOT_FOUND',
##[error]Process completed with exit code 1.
```

## How often does this happen?

Every time (100% reproducible)

## Impact

Blocker — Cannot use GSD at all

## Workaround (if any)

Move the Skip step after checkout temporarily, or revert the step body to inline bash.

## Additional context

- PR #434 introduced the broken port (check-env.sh → .cjs migration batch)
- PR #437 fixed a matrix-shell parse error that had been hiding this regression (workflow was rejected at parse before the bad step could run)
- PR #438 (matrix-shell hotfix) exposed this — was hidden while workflow rejected at parse
- **This issue will be closed by expanded PR #438**
- Related CI run: https://github.com/open-gsd/get-shit-done-redux/actions/runs/26580199043
- Blocks rc.3 release

## Privacy Checklist

- [x] I have reviewed all pasted output for PII (usernames, paths, API keys) and redacted where necessary

**Comment by trek-e** [comment]
Fix included in PR #438 (commit `9062b6c2`). Approach: revert the `Skip full-only matrix entry on PR` step from `node scripts/ci-smoke-skip.cjs` back to inline shell using env vars + $GITHUB_OUTPUT, so no file is required before checkout. Deleted the orphaned `scripts/ci-smoke-skip.cjs` since no other callers remain. Will auto-close on PR #438 merge via the `Closes #439` keyword in that PR's body.
